import './Terms.css';
function Terms() {
    return (
        <section className='terms'>
        <h1>Terms</h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat amet voluptate, sint eveniet alias accusamus asperiores doloribus cum expedita, in dolor temporibus enim quo deleniti quisquam molestias labore? Culpa, officiis reiciendis rerum eligendi nisi in quidem doloribus nulla vitae, temporibus similique. Officiis totam et quidem, sapiente dolorum voluptatum molestiae? Eaque repudiandae veniam consectetur nulla quo deleniti vero. Animi, dicta doloribus cupiditate ex repellat neque veniam sequi molestias illo ipsa iure? Voluptates eligendi nesciunt ullam alias aut exercitationem vel reiciendis ducimus totam, nostrum id error minus delectus laudantium autem excepturi suscipit architecto hic labore voluptatum deleniti sunt cumque asperiores ea? Fugiat est repudiandae ratione maiores officiis ipsum veniam, illo assumenda facilis perspiciatis provident nam animi iste dicta nisi soluta nostrum voluptatibus blanditiis earum ab, veritatis adipisci. Harum sint voluptas molestiae mollitia quaerat earum ullam, illum ut recusandae labore delectus? Laboriosam earum id ipsam. Expedita assumenda tempora corporis, necessitatibus est, ratione alias magni ea rem non ipsum esse cum totam quis sed veniam ipsa! Quia aut obcaecati et voluptatem dolorum temporibus inventore excepturi suscipit illum est ipsam, dignissimos quam quidem rerum laudantium aperiam, iste ab mollitia perspiciatis. Dolor reprehenderit ducimus sit totam labore nemo? Ullam fugit, iure quam numquam, impedit autem odio aperiam ipsa non dignissimos voluptas nostrum nesciunt illo odit minima quaerat maxime recusandae, assumenda praesentium vero. Illum repellendus, et quis ab dicta quidem iste fugit ea. Suscipit deleniti vitae in officia perspiciatis pariatur aut assumenda minima exercitationem. Nostrum debitis numquam, repellat officiis voluptas corporis voluptate expedita beatae accusantium est? Repellendus id aliquam similique voluptates ipsam ut cupiditate nemo molestias, perspiciatis recusandae sunt minus tempore ipsum quos impedit ea quae rerum aliquid vero consequuntur quibusdam minima tempora! Numquam exercitationem quasi, odit sequi perferendis reprehenderit incidunt similique libero rerum qui praesentium assumenda dignissimos corporis. Tenetur placeat corporis assumenda in architecto itaque repellat eveniet, a fugit harum nemo beatae voluptatem recusandae quasi ad iusto rem laborum cupiditate cumque commodi. Numquam facilis et obcaecati! Ea, dolorem nostrum nulla placeat velit mollitia id delectus iusto, tempore sapiente alias, quia consequatur nam! Qui, numquam, minima cum molestiae quis et architecto, sed amet iure modi facilis voluptatum!</p>
    </section>
    );
}
export default Terms;