# Generated by Django 4.2.1 on 2023-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0002_alter_news_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title", "id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="photo",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
