# Generated by Django 4.2.1 on 2023-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0003_alter_category_options_photo_title_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="news_comments", to="news_api.comment"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="news_likes", to="news_api.comment"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="photos",
            field=models.ManyToManyField(blank=True, to="news_api.photo"),
        ),
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, to="news_api.tag"),
        ),
        migrations.AlterField(
            model_name="news",
            name="videos",
            field=models.ManyToManyField(blank=True, to="news_api.video"),
        ),
    ]
