# Generated by Django 4.2.1 on 2023-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0005_image_likes_rename_is_activ_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, to="news_api.tag"),
        ),
    ]
