# Generated by Django 4.2.1 on 2023-05-18 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0006_news_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="likes",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="likes",
            name="news",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="news_api.news",
            ),
        ),
    ]
