# Generated by Django 4.2.1 on 2023-05-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0007_likes_created_at_alter_likes_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="comments",
            field=models.ManyToManyField(
                related_name="related_news", to="news_api.comment"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="news",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_comments",
                to="news_api.news",
            ),
        ),
    ]
