# Generated by Django 4.2.1 on 2023-05-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0014_alter_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
